JC=javac
JFLAGS = -g

Main.class: Main.java Match.java Sport.java Championnat.java EFoot.java EFutsal.java EHand.java Equipe.java ERugby.java EVolley.java
	$(JC) $(JFLAGS) Main.java Match.java Sport.java Championnat.java EFoot.java EFutsal.java EHand.java Equipe.java ERugby.java EVolley.java

